//Generado por tools/originalTexts.py desde el dr.exe original. No editar a mano.
#include "originalTexts.h"

//sponsorWinStreakTexts: 6 variantes de 10 lineas, desde 0x447388
const char sponsorWinStreakTexts[6][10][80] = {
  {
    "",
    "",
    "[Not too shabby, driver.",
    "",
    "[Your wild winning streak has earned",
    "[you an extra 600 bucks.{ But don't",
    "get cocky, those other wannabe",
    "victory hounds are going to zero",
    "right into your blazing taillights.",
    "And they want to get you bad.",
  },
  {
    "",
    "",
    "[Not too shabby, driver.",
    "",
    "[Your wild winning streak has earned",
    "[you an extra 1,000 bucks.{ But don't",
    "get cocky, those other wannabe",
    "victory hounds are going to zero",
    "right into your blazing taillights.",
    "And they want to get you bad.",
  },
  {
    "",
    "",
    "[Not too shabby, driver.",
    "",
    "[Your wild winning streak has earned",
    "[you an extra 2,000 bucks.{ But don't",
    "get cocky, those other wannabe",
    "victory hounds are going to zero",
    "right into your blazing taillights.",
    "And they want to get you bad.",
  },
  {
    "",
    "",
    "[Not too shabby, driver.",
    "",
    "[Your wild winning streak has earned",
    "[you an extra 3,000 bucks.{ But don't",
    "get cocky, those other wannabe",
    "victory hounds are going to zero",
    "right into your blazing taillights.",
    "And they want to get you bad.",
  },
  {
    "",
    "",
    "[Not too shabby, driver.",
    "",
    "[Your wild winning streak has earned",
    "[you an extra 4,000 bucks.{ But don't",
    "get cocky, those other wannabe",
    "victory hounds are going to zero",
    "right into your blazing taillights.",
    "And they want to get you bad.",
  },
  {
    "",
    "",
    "[Not too shabby, driver.",
    "",
    "[Your wild winning streak has earned",
    "[you an extra 5,000 bucks.{ But don't",
    "get cocky, those other wannabe",
    "victory hounds are going to zero",
    "right into your blazing taillights.",
    "And they want to get you bad.",
  },
};

//sponsorNoPaintJobTexts: 6 variantes de 10 lineas, desde 0x448648
const char sponsorNoPaintJobTexts[6][10][80] = {
  {
    "",
    "",
    "[Inconceivable, driver!",
    "",
    "It was a snowball's chance in hell.",
    "Through that blitzkrieg battle, and",
    "[not a shadow of a scratch on your",
    "[paint job.{ My bet was on you, and",
    "it paid me back big time. Here, [your",
    "[share{, [$350{. Go knock yourself out.",
  },
  {
    "",
    "",
    "[Inconceivable, driver!",
    "",
    "It was a snowball's chance in hell.",
    "Through that blitzkrieg battle, and",
    "[not a shadow of a scratch on your",
    "[paint job.{ My bet was on you, and",
    "it paid me back big time. Here, [your",
    "[share{, [$750{. Go knock yourself out.",
  },
  {
    "",
    "",
    "[Inconceivable, driver!",
    "",
    "It was a snowball's chance in hell.",
    "Through that blitzkrieg battle, and",
    "[not a shadow of a scratch on your",
    "[paint job.{ My bet was on you, and",
    "it paid me back big time. Here, [your",
    "[share{, [$1,500{. Go knock yourself out.",
  },
  {
    "",
    "",
    "[Inconceivable, driver!",
    "",
    "It was a snowball's chance in hell.",
    "Through that blitzkrieg battle, and",
    "[not a shadow of a scratch on your",
    "[paint job.{ My bet was on you, and",
    "it paid me back big time. Here, [your",
    "[share, [$3,000{. Go knock yourself out.",
  },
  {
    "",
    "",
    "[Inconceivable, driver!",
    "",
    "It was a snowball's chance in hell.",
    "Through that blitzkrieg battle, and",
    "[not a shadow of a scratch on your",
    "[paint job.{ My bet was on you, and",
    "it paid me back big time. Here, [your",
    "[share, [$4,500{. Go knock yourself out.",
  },
  {
    "",
    "",
    "[Inconceivable, driver!",
    "",
    "It was a snowball's chance in hell.",
    "Through that blitzkrieg battle, and",
    "[not a shadow of a scratch on your",
    "[paint job.{ My bet was on you, and",
    "it paid me back big time. Here, [your",
    "[share, [$6,000{. Go knock yourself out.",
  },
};

//sponsorAllCarsCrashTexts: 6 variantes de 10 lineas, desde 0x449908
const char sponsorAllCarsCrashTexts[6][10][80] = {
  {
    "",
    "",
    "[I am one grateful reaper, driver.",
    "",
    "[More car corpses{ for my domain. You",
    "are my sweetest minion. Your dead-",
    "serious dedication has earned you",
    "a parking space among my horsemen.",
    "[A bonus of $600 to you{, horse-",
    "powered serial-auto-killer.",
  },
  {
    "",
    "",
    "[I am one grateful reaper, driver.",
    "",
    "[More car corpses{ for my domain. You",
    "are my sweetest minion. Your dead-",
    "serious dedication has earned you",
    "a parking space among my horsemen.",
    "[A bonus of $1,000 to you{, horse-",
    "powered serial-auto-killer.",
  },
  {
    "",
    "",
    "[I am one grateful reaper, driver.",
    "",
    "[More car corpses{ for my domain. You",
    "are my sweetest minion. Your dead-",
    "serious dedication has earned you",
    "a parking space among my horsemen.",
    "[A bonus of $2,000 to you{, horse-",
    "powered serial-auto-killer.",
  },
  {
    "",
    "",
    "[I am one grateful reaper, driver.",
    "",
    "[More car corpses{ for my domain. You",
    "are my sweetest minion. Your dead-",
    "serious dedication has earned you",
    "a parking space among my horsemen.",
    "[A bonus of $3,000 to you{, horse-",
    "powered serial-auto-killer.",
  },
  {
    "",
    "",
    "[I am one grateful reaper, driver.",
    "",
    "[More car corpses{ for my domain. You",
    "are my sweetest minion. Your dead-",
    "serious dedication has earned you",
    "a parking space among my horsemen.",
    "[A bonus of $4,000 to you{, horse-",
    "powered serial-auto-killer.",
  },
  {
    "",
    "",
    "[I am one grateful reaper, driver.",
    "",
    "[More car corpses{ for my domain. You",
    "are my sweetest minion. Your dead-",
    "serious dedication has earned you",
    "a parking space among my horsemen.",
    "[A bonus of $5,000 to you{, horse-",
    "powered serial-auto-killer.",
  },
};

//loanGrantedTexts: 6 variantes de 6 lineas, desde 0x452528
const char loanGrantedTexts[6][6][40] = {
  {
    "[Loan of $12,000 granted.",
    "",
    "You have 3 races to pay me back the",
    "[$18,000{. Fair is fair [<GRIN>{.",
    "",
    "Press [ESC{ to go back to the shop.",
  },
  {
    "[Loan of $9,000 granted.",
    "",
    "You have 3 races to pay me back the",
    "[$13,500{. Fair is fair [<GRIN>{.",
    "",
    "Press [ESC{ to go back to the shop.",
  },
  {
    "[Loan of $6,000 granted.",
    "",
    "You have 3 races to pay me back the",
    "[$9,000{. Fair is fair [<GRIN>{.",
    "",
    "Press [ESC{ to go back to the shop.",
  },
  {
    "[Loan of $3,000 granted.",
    "",
    "You have 3 races to pay me back the",
    "[$4,500{. Fair is fair [<GRIN>{.",
    "",
    "Press [ESC{ to go back to the shop.",
  },
  {
    "[Loan of $1,500 granted.",
    "",
    "You have 3 races to pay me back the",
    "[$2,250{. Fair is fair [<GRIN>{.",
    "",
    "Press [ESC{ to go back to the shop.",
  },
  {
    "[Loan denied, Vagabond driver.",
    "",
    "This is a business, not a charity.",
    "We don't invest in unproven wild",
    "cards. So buzz off, bug.",
    "",
  },
};

//loanOfferTexts: 6 variantes de 6 lineas, desde 0x452078
const char loanOfferTexts[6][6][40] = {
  {
    "[Borrow $12,000 - Pay $18,000",
    "",
    "With better gear you'd already be",
    "on the top, eh? So how does a",
    "short-term loan of [$12,000{ sound?",
    "",
  },
  {
    "[Borrow $9,000 - Pay $13,500",
    "",
    "With better gear you'd already be",
    "on the top, eh? So how does a",
    "short-term loan of [$9,000{ sound?",
    "",
  },
  {
    "[Borrow $6,000 - Pay $9,000",
    "",
    "With better gear you'd already be",
    "on the top, eh? So how does a",
    "short-term loan of [$6,000{ sound?",
    "",
  },
  {
    "[Borrow $3,000 - Pay $4,500",
    "",
    "With better gear you'd already be",
    "on the top, eh? So how does a",
    "short-term loan of [$3,000{ sound?",
    "",
  },
  {
    "[Borrow $1,500 - Pay $2,250",
    "",
    "With better gear you'd already be",
    "on the top, eh? So how does a",
    "short-term loan of [$1,500{ sound?",
    "",
  },
  {
    "[Loan of $12,000 granted.",
    "",
    "You have 3 races to pay me back the",
    "[$18,000{. Fair is fair [<GRIN>{.",
    "",
    "Press [ESC{ to go back to the shop.",
  },
};
